repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(kvstore_pb2.*\.py|kvstore_pb2_grpc.*\.py)$
      - id: end-of-file-fixer
        exclude: ^(kvstore_pb2.*\.py|kvstore_pb2_grpc.*\.py)$
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
        exclude: ^(kvstore_pb2.*\.py|kvstore_pb2_grpc.*\.py)$
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.7
    hooks:
      - id: uv-lock
        pass_filenames: false
      - id: uv-audit

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix, --verbose]
        exclude: ^(kvstore_pb2.*\.py|kvstore_pb2_grpc.*\.py)$
      - id: ruff-format
        exclude: ^(kvstore_pb2.*\.py|kvstore_pb2_grpc.*\.py)$
